### ISSUE TITLE
Unsupport Some Version

### ISSUE THREAD

**Issue by channarit1994** [Elem8100/GM-HandTool#2]
![image](https://user-images.githubusercontent.com/12149565/107117014-d9563780-68a9-11eb-9ac1-ed03d8e7cdd1.png)

I got a problem when i load Character.wz but Item.wz it's ok. I use EMS/MSEA old version

**Comment by Elem8100** [comment]
Worked fine with MSEA 082. Can you provide the download link ?

**Comment by channarit1994** [comment]
> Worked fine with MSEA 082. Can you provide the download link ?

https://mpz.testbug.io/full/NeoMapleZ_v77.rar

**Comment by Elem8100** [comment]
It's seem to  modified version of WZ file. The Wz lib only support standard/official version of WZ.
There is no way to fix that.
